# @package _global_
solver:
  name: "fmmax"
  type: "rcwa"

  params:
    fourier_order: [9, 9]
    fmm_formulation: "jones"
    dtype: "complex64"

  stability:
    precision_strategy: "mixed"
    energy_check:
      enabled: true
      tolerance: 0.02
